package org.itri.view.humanhealth.hibernate;
// Generated 2020/4/24 �U�� 08:59:27 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientInfo generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "patient_info")
public class PatientInfo implements java.io.Serializable {

	private long patientInfoId;
	private Users users;
	private Patient patient;
	private String name;
	private String gender;
	private String age;
	private String idNum;
	private boolean isDeleted;
	private Date timeCreated;
	private Date lastUpdated;

	public PatientInfo() {
	}

	public PatientInfo(long patientInfoId, Users users, Patient patient, String name, String gender, String age,
			String idNum, boolean isDeleted, Date timeCreated) {
		this.patientInfoId = patientInfoId;
		this.users = users;
		this.patient = patient;
		this.name = name;
		this.gender = gender;
		this.age = age;
		this.idNum = idNum;
		this.isDeleted = isDeleted;
		this.timeCreated = timeCreated;
	}

	public PatientInfo(long patientInfoId, Users users, Patient patient, String name, String gender, String age,
			String idNum, boolean isDeleted, Date timeCreated, Date lastUpdated) {
		this.patientInfoId = patientInfoId;
		this.users = users;
		this.patient = patient;
		this.name = name;
		this.gender = gender;
		this.age = age;
		this.idNum = idNum;
		this.isDeleted = isDeleted;
		this.timeCreated = timeCreated;
		this.lastUpdated = lastUpdated;
	}

	@SequenceGenerator(name="patient_info_seq", sequenceName="patient_info_patient_info_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="patient_info_seq")	@Id

	@Column(name = "patient_info_id", unique = true, nullable = false)
	public long getPatientInfoId() {
		return this.patientInfoId;
	}

	public void setPatientInfoId(long patientInfoId) {
		this.patientInfoId = patientInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "name", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", nullable = false, length = 32)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "age", nullable = false, length = 64)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "id_num", nullable = false, length = 32)
	public String getIdNum() {
		return this.idNum;
	}

	public void setIdNum(String idNum) {
		this.idNum = idNum;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", nullable = false, length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
