package org.itri.view.humanhealth.hibernate;

import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SurveyQuestionChoice generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "survey_question_choice")
public class SurveyQuestionChoice implements java.io.Serializable {

	private long surveyQuestionChoiceId;
	private String surveyQuestionChoiceText;
	private boolean isDeleted;
	private long surveyQuestionId;

	public SurveyQuestionChoice() {
	}

	public SurveyQuestionChoice(long surveyQuestionChoiceId, String surveyQuestionChoiceText, boolean isDeleted,
			long surveyQuestionId) {
		this.surveyQuestionChoiceId = surveyQuestionChoiceId;
		this.surveyQuestionChoiceText = surveyQuestionChoiceText;
		this.isDeleted = isDeleted;
		this.surveyQuestionId = surveyQuestionId;
	}

	@SequenceGenerator(name="survey_question_choice_seq", sequenceName="survey_question_choice_survey_question_choice_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="survey_question_choice_seq")	@Id

	@Column(name = "survey_question_choice_id", unique = true, nullable = false)
	public long getSurveyQuestionChoiceId() {
		return this.surveyQuestionChoiceId;
	}

	public void setSurveyQuestionChoiceId(long surveyQuestionChoiceId) {
		this.surveyQuestionChoiceId = surveyQuestionChoiceId;
	}

	@Column(name = "survey_question_choice_text", nullable = false, length = 1024)
	public String getSurveyQuestionChoiceText() {
		return this.surveyQuestionChoiceText;
	}

	public void setSurveyQuestionChoiceText(String surveyQuestionChoiceText) {
		this.surveyQuestionChoiceText = surveyQuestionChoiceText;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "survey_question_id", nullable = false)
	public long getSurveyQuestionId() {
		return this.surveyQuestionId;
	}

	public void setSurveyQuestionId(long surveyQuestionId) {
		this.surveyQuestionId = surveyQuestionId;
	}

}
